name: Build and deploy HTML files to Azure Web App - LABOAUTONOMIA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Pasos para generar archivos HTML
      - name: Generate HTML files
        run: |
          mkdir -p ./html-output
          echo "<html><body><h1>Hello, World!</h1></body></html>" > ./html-output/index.html

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: html-files
          path: ./html-output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: html-files

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'LABOAUTONOMIA'
